project:
  type: website

website:
  title: "The MockUp"
  description: "Data science tips brought to you by Tom Mock"
  favicon: themockup.png
  image: themockup.png
  twitter-card: true
  open-graph: true
  site-url: https://themockup.blog/
  comments:
    utterances:
      repo: jthomasmock/mockup-blog
  navbar:
    search: true
    right:
      - text: "Blog"
        file: index.qmd
      - text: "Resources"
        file: static/resources/resources.qmd
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/jthomasmock
      - icon: twitter
        href: https://twitter.com/thomas_mock
      - icon: fa fa-rss
        href: index.xml
format:
  html:
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    mainfont: "Lato"
    monofont: "Fira Mono"
    footnotes-hover: true
    fontsize: 1em
    theme: my-litera.scss
    css: styles.css
