---
title: "Building a blog with Distill"
description: |
  An alternative to blogdown.
author:
  - name: Thomas Mock
    url: https://example.com/norajones
date: 12-13-2018
output: 
  distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This is the HIGHLY unofficial companion guide to Allison Hill's amazing [Up and running with `blogdown`](https://alison.rbind.io/post/up-and-running-with-blogdown/) guide but for `radix`.

From RStudio's [`Radix` package website]():

Radix is an online publication format designed for scientific and technical communication. Radix articles include:

* Reader-friendly typography that adapts well to mobile devices.
* Features essential to technical writing like LaTeX math, citations, and footnotes.
* Flexible figure layout options (e.g. displaying figures at a larger width than the article text).
* Attractively rendered tables with optional support for pagination.
* Support for a wide variety of diagramming tools for illustrating concepts.
* The ability to incorporate JavaScript and D3-based interactive visualizations.
* A variety of ways to publish articles, including support for **publishing sets of articles as a Radix website**.
* The ability to **create a blog composed of a collection of Radix articles**.
* Radix is based on the Distill web framework, which was originally created for use in the Distill Machine Learning Journal. Radix combines the technical authoring features of Distill with R Markdown, enabling a fully reproducible workflow based on literate programming.

Basically this is a long way of saying `radix` is good for literate programming AND good for creating extremely light-weight Hugo-independent websites and blogs. Hugo is the biggest pain point that I and others have run into when creating and maintaining a blog/website through `blogdown`.

That being said - Hugo comes with all sorts of goodies/customizations, so if it is working for you I'd say stick with it!

# 1 Read up on `radix`

Before you start, I recommend reading the following:
* `radix`:[Creating a Blog](https://rstudio.github.io/radix/blog.html) 

# 2 Create accounts

You will need:
* A publishing service (RStudio Connect, Github Pages, Netlify, etc)
* A version control account (Github, Gitlab, etc)

I already had Netlify and Github accounts, so I went down that route!