---
title: "An ode to stringr"
description: |
  A deep dive on string functions!
author:
  - name: Thomas Mock
    url: https://themockup.netlify.com/
date: 04-03-2020
output: 
  distill::distill_article
draft: true
---

```{r setup, include=FALSE}
library(tidyverse)
pets <- tibble::tibble(name = c("Howard", "Fluffy", "Bella", "Charlie", "Peanut", "Molly"),
                       sex = c("Male", "Female", "Female", "Male", "Male", "Female"),
                       breed = c("Boston Terrier", "Persian", "Boxer", "American Shorthair", "Beagle", "Russian Blue"),
                       species = c("DOG", "cat", "DOG", "CaT", "DOg", "cAT"))
```
### invert_match()

Invert match is 
```{r, echo = F}
pets <- pets %>% 
  mutate(species = tolower(species))
```

```{r}
pets %>% 
  filter(invert_match(species, "dog"))
stringtibble::as_tibble(x = )
stringr::invert_match()
```

```{r}
numbers <- "1 and 2 and 4 and 456"
num_loc <- str_locate_all(numbers, "[0-9]+")[[1]]
str_sub(numbers, num_loc[, "start"], num_loc[, "end"])

text_loc <- invert_match(num_loc)
str_sub(numbers, text_loc[, "start"], text_loc[, "end"])

```

```{r}
stringr::str_c("cat", "face")
paste0("cat", "face")
```
```{r}
stringr::str_conv()
```
```{r}
stringr::str_count()
```
```{r}
stringr::str_detect()
```
```{r}
stringr::str_dup()
```
```{r}
stringr::str_extract()
```
```{r}
stringr::str_flatten()
```
```{r}
stringr::str_glue()
```
```{r}
stringr::str_length()
```
```{r}
stringr::str_locate()
```
```{r}
stringr::str_match()
```
```{r}
stringr::str_order()
```
```{r}
stringr::str_pad()
```
```{r}
stringr::str_remove()
```
```{r}
stringr::str_replace()
```
```{r}
stringr::str_replace_na()
```
```{r}
stringr::str_split()
```
```{r}
stringr::str_sub()
```
```{r}
stringr::str_subset()
```
```{r}
stringr::str_trim()
```
```{r}
stringr::str_trunc()
```
```{r}
stringr::str_view()
```
```{r}
stringr::str_wrap
```
```{r}
stringr::word()
```

